name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: yarn -v
    - run: yarn tsc --noEmit
    - run: yarn test
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash)
